/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.miniaturesolid;

import org.apache.catalina.startup.Tomcat;
import org.apache.catalina.webresources.DirResourceSet;
import org.apache.catalina.webresources.StandardRoot;

import java.io.File;
import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.WebResourceRoot;

public class App {
    public static void main(String[] args) {
        Tomcat tomcat = new Tomcat();
        tomcat.setPort(8080);
        tomcat.getConnector();

        File publicFolder = new File("src/main/webapp");
        if (!publicFolder.exists()) {
            publicFolder.mkdirs();
        }

        Context context = tomcat.addWebapp("", publicFolder.getAbsolutePath());
        context.setReloadable(true);

        File classesFolder = new File("build/classes/java/main");
        WebResourceRoot resources = new StandardRoot(context);
        resources.addPreResources(
                new DirResourceSet(resources, "/WEB-INF/classes", classesFolder.getAbsolutePath(), "/"));
        context.setResources(resources);
        context.addWelcomeFile("index.html");
        try {
            tomcat.start();
        } catch (LifecycleException e) {
            e.printStackTrace();
        }
        tomcat.getServer().await();
    }
}
